### ISSUE TITLE
epic2-bw  KeyError: 'mapq'

### ISSUE THREAD

**Issue by YichaoOU** [biocore-ntnu/epic2#21]
When running with bam files (-t 1.bam -c 2.bam). I got the following error.

Traceback (most recent call last):
  File "/home/yli11/.conda/envs/diffPeaks/bin/epic2-bw", line 174, in <module>
    main(args)
  File "/home/yli11/.conda/envs/diffPeaks/lib/python3.7/site-packages/epic2/bigwig.py", line 97, in main
    treatment_ranges = files_to_coverage(args["treatment"], args)
  File "/home/yli11/.conda/envs/diffPeaks/lib/python3.7/site-packages/epic2/bigwig.py", line 72, in files_to_coverage
    ranges = file_to_ranges(f, args, "ChIP")
  File "/home/yli11/.conda/envs/diffPeaks/lib/python3.7/site-packages/epic2/bigwig.py", line 41, in file_to_binned_ranges
    bin_counts, _ = files_to_bin_counts([f], args, datatype)
  File "epic2/src/reads_to_bins.pyx", line 183, in epic2.src.reads_to_bins.files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 225, in epic2.src.reads_to_bins.files_to_bin_counts
KeyError: 'mapq'

**Comment by YichaoOU** [comment]
I think the reason is probably paired-end bam file since I'm using ATAC-seq.

**Comment by endrebak** [comment]
epic2 does not support paired end bam yet. I should look into fixing this
(or at least warning the user.)

**Comment by endrebak** [comment]
(Reopening this because what you found is an actual bug. Thanks!)

**Comment by jmano035** [comment]
Hi endrebak, 

I'm using epic2-bw version 0.0.50 and also getting this same mapq error (see below). Has the bug been fixed?

(julianam) (base) [julianam@gra-login3 testdata]$ epic2-bw -t ~/scratch/testdata/sample.sorted.aligned684TIAchiptn.bam -c ~/scratch/testdata/sample.sorted.aligned684TIAinput.bam -bw bigwigs/
Traceback (most recent call last):
  File "/home/julianam/bin/epic2-bw", line 182, in <module>
    main(args)
  File "/home/julianam/lib/python3.6/site-packages/epic2/bigwig.py", line 113, in main
    treatment_ranges = files_to_coverage(args["treatment"], args)
  File "/home/julianam/lib/python3.6/site-packages/epic2/bigwig.py", line 75, in files_to_coverage
    ranges = file_to_ranges(f, args, "ChIP")
  File "/home/julianam/lib/python3.6/site-packages/epic2/bigwig.py", line 44, in file_to_binned_ranges
    bin_counts, _ = files_to_bin_counts([f], args, datatype)
  File "epic2/src/reads_to_bins.pyx", line 218, in epic2.src.reads_to_bins.files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 248, in epic2.src.reads_to_bins.files_to_bin_counts
KeyError: 'mapq'

**Comment by endrebak** [comment]
Tried to fix it now :) 0.0.51 is uploaded
