### ISSUE TITLE
Linux install error

### ISSUE THREAD

**Issue by radio1988** [biocore-ntnu/epic2#27]
My installation command history
```
1. install anaconda
2. conda create -y -n py35 python=3.5 anaconda
3. conda activate py35
4. conda install epic2
5. conda install -c bioconda epic2
```

Error message: 
```
Traceback (most recent call last):
  File "/home/rl44w/anaconda3/envs/py35/bin/epic2", line 10, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 14, in init epic2.src.reads_to_bins
  File "libchtslib.pxd", line 2590, in init epic2.src.read_bam
ValueError: pysam.libchtslib.HTSFile size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

I'm working in centOS

**Comment by radio1988** [comment]
after creating a brand new py36 environment with the following command and install epic2, the problem was solved
```
conda create -y -n py36 python=3.6 anaconda
conda activate py36
conda install -c bioconda epic2
```

**Comment by endrebak** [comment]
Thanks! I was about to comment that it seems that the htslib header was different from when epic2 was installed.  But I am not a C-wiz.
