### ISSUE TITLE
Library not loaded - Reason Image not found error

### ISSUE THREAD

**Issue by sufyazi** [biocore-ntnu/epic2#51]
Hi 

I need help with running my first epic2 command. I installed everything right (seemingly) but when I tried to run this command the terminal threw up this error. See snippets below.

```
epic2 -t /Users/sufyazi/Bioinformatics/PhD_works/bed_version/H2AZ_3CR1_39_aligned.sorted.bed -c /Users/sufyazi/Bioinformatics/PhD_works/bed_version/INPUT_3CR1_37_aligned.sorted.bed -egf 0.98 -cs /Users/sufyazi/Bioinformatics/PhD_works/BDP2_project/genome_db/Pf3D7v34_chrom_sizes.txt -o /Users/sufyazi/Bioinformatics/PhD_works/epic2_output/H2AZ_3CR1_epic2_called_peaks.bed
```
And here's the error

```
Traceback (most recent call last):
  File "/Users/sufyazi/opt/anaconda3/bin/epic2", line 10, in <module>
    from epic2.main import _main
  File "/Users/sufyazi/opt/anaconda3/lib/python3.8/site-packages/epic2/main.py", line 5, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 17, in init epic2.src.reads_to_bins
ImportError: dlopen(/Users/sufyazi/opt/anaconda3/lib/python3.8/site-packages/epic2/src/read_bam.cpython-38-darwin.so, 2): Library not loaded: @rpath/libctabixproxies.cpython-38-darwin.so
  Referenced from: /Users/sufyazi/opt/anaconda3/lib/python3.8/site-packages/epic2/src/read_bam.cpython-38-darwin.so
  Reason: image not found
```

I have tried googling and checking past issues but to no avail. Can someone help?

**Comment by sufyazi** [comment]
I solved my own problem. This issue arose because my base anaconda was messed up. Created an env and installed all dependencies and then installed epic2 in it and now the code works! Sorry!

**Comment by endrebak** [comment]
Thanks for reporting. Great that you were able to figure it out yourself :)
