### ISSUE TITLE
`epic2-bw` failed with KeyError: 'guess_bampe' 

### ISSUE THREAD

**Issue by xie186** [biocore-ntnu/epic2#52]
Hi, thanks for developing epic2. I'm not to successfully run the example data generated from `epic2-bw --example`. Here are the error message: 
```
Traceback (most recent call last):
  File "/group/bioinfo/apps/apps/miniconda-4.8.2/envs/epic2-0.0.48/bin/epic2-bw", line 174, in <module>
    main(args)
  File "/group/bioinfo/apps/apps/miniconda-4.8.2/envs/epic2-0.0.48/lib/python3.9/site-packages/epic2/bigwig.py", line 100, in main
    treatment_ranges = files_to_coverage(args["treatment"], args)
  File "/group/bioinfo/apps/apps/miniconda-4.8.2/envs/epic2-0.0.48/lib/python3.9/site-packages/epic2/bigwig.py", line 75, in files_to_coverage
    ranges = file_to_ranges(f, args, "ChIP")
  File "/group/bioinfo/apps/apps/miniconda-4.8.2/envs/epic2-0.0.48/lib/python3.9/site-packages/epic2/bigwig.py", line 44, in file_to_binned_ranges
    bin_counts, _ = files_to_bin_counts([f], args, datatype)
  File "epic2/src/reads_to_bins.pyx", line 218, in epic2.src.reads_to_bins.files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 240, in epic2.src.reads_to_bins.files_to_bin_counts
KeyError: 'guess_bampe'

```

Could you please solve this issue? Thank you in advance!

**Comment by endrebak** [comment]
Will look at. Thanks for notifying me

**Comment by endrebak** [comment]
0.0.49 should be out soon. Mind checking if it works for you now? :)

**Comment by xie186** [comment]
Thank you for your quick response. 

```
Python 3.7.4
pip uninstall epic2  ## Successfully installed epic2-0.0.49
~/.local/bin/epic2-bw -t ~/.local/lib/python3.7/site-packages/epic2/examples/test.bed.gz -c ~/.local/lib/python3.7/site-packages/epic2/examples/control.bed.gz -bw bigwigs/ -i2bw log2fc_bigwigs/ -cbw chip.bw -ibw input.bw -2bw log2_chip_input.bw
```

Error message:
```
Traceback (most recent call last):
  File "/home/xie186/.local/bin/epic2-bw", line 182, in <module>
    main(args)
  File "/home/xie186/.local/lib/python3.7/site-packages/epic2/bigwig.py", line 132, in main
    ranges.to_bigwig(bw_name, chromsizes, divide_by=control_sum)
TypeError: to_bigwig() got an unexpected keyword argument 'divide_by'

```

**Comment by endrebak** [comment]
Thanks for your reply. I've tried fixing this in 0.0.50. But I have no way to test the code on my machine as I have not set up a proper Python env on my new M1 mac.

Please tell me if it works or not :)
