### ISSUE TITLE
epic2 Failed to install on Mac

### ISSUE THREAD

**Issue by jjp55** [biocore-ntnu/epic2#53]
Hello, 

I am trying to install epic2 on my Mac running macOS Big Sur. I am installing the package in a new anaconda environment using:
pip install Cython 
pip install pusam
pip install epic2

All packages say they installed without throwing up any errors. 

When I run epic2 -h I receive the following message

Traceback (most recent call last):
  File "/Users/jjp/opt/anaconda3/envs/epic2/bin/epic2", line 10, in <module>
    from epic2.main import _main
  File "/Users/jjp/opt/anaconda3/envs/epic2/lib/python3.9/site-packages/epic2/main.py", line 5, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 17, in init epic2.src.reads_to_bins
ImportError: dlopen(/Users/jjp/opt/anaconda3/envs/epic2/lib/python3.9/site-packages/epic2/src/read_bam.cpython-39-darwin.so, 2): Library not loaded: @rpath/libctabixproxies.cpython-39-darwin.so
  Referenced from: /Users/jjp/opt/anaconda3/envs/epic2/lib/python3.9/site-packages/epic2/src/read_bam.cpython-39-darwin.so
  Reason: image not found

I am not sure what is causing this error, but any suggestions or help would be greatly appreciated.

**Comment by boyoung-shin** [comment]
Hello, I am getting the same error on my MacOS (Catalina).  I would also appreciate any suggestions!

**Comment by endrebak** [comment]
Thanks for the heads-up. I've been able to reproduce and have started to look into it :)

**Comment by endrebak** [comment]
https://github.com/biocore-ntnu/epic2/issues/51 references the same issue. I'll try his fix (creating new env)

**Comment by endrebak** [comment]
Asked here: https://groups.google.com/g/pysam-user-group/c/jNATBiEIfNw

**Comment by jjp55** [comment]
Thank you for asking. I tried creating a new environment and still got the same answer. 

The code I ran was: 
conda create --name epic 
conda activate epic
pip install Cython 
pip install pysam 
pip install epic2

All of them said they successfully installed, but I again received the same error when using epic -h . I'll keep watching here and on the google groups for updates

**Comment by endrebak** [comment]
I really want to support macos also. I should look at alternative installation methods in case something like this happens again (providing an easy to run image with epic2 for example)

**Comment by endrebak** [comment]
Note to self: https://biocontainers-edu.readthedocs.io/en/latest/conda_integration.html

Investigate whether it is possible to run epic2 with singularity using an image from biocontainers.
