### ISSUE TITLE
ValueError: need more than 0 values to unpack

### ISSUE THREAD

**Issue by chenchen-eng** [biocore-ntnu/epic2#54]
I found an error, how can I solve it?
Found a median fragment size of 382336.5
 
Traceback (most recent call last):
  File "/users/xulab/zy/soft/miniconda3/bin/epic2", line 257, in <module>
    _main(args)
  File "/users/xulab/zy/soft/miniconda3/lib/python3.9/site-packages/epic2/main.py", line 35, in _main
    effective_genome_length, chromsizes = egl_and_chromsizes(args)
  File "epic2/src/genome_info.pyx", line 336, in epic2.src.genome_info.egl_and_chromsizes
  File "epic2/src/genome_info.pyx", line 252, in epic2.src.genome_info.create_genome_size_dict_custom_genome
ValueError: need more than 0 values to unpack
thanks

**Comment by endrebak** [comment]
Thanks for reporting! Could you please post the custom genome file you are using? It seems like epic2 does not understand it :)
