### ISSUE TITLE
Error running epic2 v0.0.52

### ISSUE THREAD

**Issue by benayang** [biocore-ntnu/epic2#57]
I installed epic2 v0.0.52 into a conda environment with python 3.7.3, but ran into the following error when I tried to run it. My pysam package should be up to date (v0.17.0).

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/epic2/bin/epic2", line 10, in <module>
    from epic2.main import _main
  File "/opt/miniconda3/envs/epic2/lib/python3.7/site-packages/epic2/main.py", line 5, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 17, in init epic2.src.reads_to_bins
  File "epic2/src/read_bam.pyx", line 1, in init epic2.src.read_bam
AttributeError: module 'pysam.libcalignmentfile' has no attribute 'PileupColumn'
```

**Comment by endrebak** [comment]
macOS or linux?

**Comment by benayang** [comment]
I'm using Ubuntu 18.04.

--
Benjamin Yang
BME PhD Student

P: (408) 608-9888 | E: ***@***.***

**Comment by endrebak** [comment]
This is weird. Pysam must have changed under my feet because it has worked
fine until now. Perhaps I should peg an earlier pysam version? I should
create a way for users to use bed if they have pysam-problems.

Anyways, I do not have time to investigate this until two weeks from now.
Sorry! I'll get around to it after my exam.

**Comment by benayang** [comment]
Thank you! I also tried using epic2 v0.0.41 from bioconda in the same conda environment but ran into the following error with both the provided example bedpe and bed files. Is there a way to fix this?

epic2 -t example/test.bed -c example/control.bed 
```
Found a median readlength of 25.0
 
Using genome hg19.
 
Using an effective genome length of ~2510 * 1e6
 
Parsing ChIP file(s): 
  example/test.bed 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by benayang** [comment]
Installing epic2 v0.0.52 via pip instead of conda seems to fix both errors!

**Comment by endrebak** [comment]
Hooray! Thanks for reporting :)
