### ISSUE TITLE
Epic2 running error caused by chromosome names in my alignment file

### ISSUE THREAD

**Issue by sitr1014** [biocore-ntnu/epic2#62]
Hi, I got an error when running epic2 as below:
--- Logging error ---
Traceback (most recent call last):
  File "/panfs/roc/msisoft/anaconda/python3-2020.07-mamba/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/panfs/roc/msisoft/anaconda/python3-2020.07-mamba/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/panfs/roc/msisoft/anaconda/python3-2020.07-mamba/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/panfs/roc/msisoft/anaconda/python3-2020.07-mamba/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/tretyako/hanxx963/.local/bin/epic2", line 257, in <module>
    _main(args)
  File "/home/tretyako/hanxx963/.local/lib/python3.8/site-packages/epic2/main.py", line 39, in _main
    c_bins_counts, chip_count_before = files_to_bin_counts(
Message: 'Chromosome'
Arguments: ('chrGL000008.2', 'not in the chromosome sizes:', 'chr1, chr2, chr3, chr4, chr5, chr6, chr7, chrX, chr8, chr9, chr11, chr10, chr12, chr13, chr14, chr15, chr16, chr17, chr18, chr20, chr19, chrY, chr22, chr21, chrM')

I think this is because there are some weird alignment result in my bed file. I did get an output file just showing result in chr1 to chrY but I am also wondering if this error would affect anything? I assumed these weirdly aligned reads were just ignored when calling peaks?

**Comment by endrebak** [comment]
I think it is better to warn the user of unexpected chromosomes. You should remove the non-canonical chromosomes yourself before running epic2.

The error probably means that chr X, Y and M were not output.

Thanks for asking :D
