### ISSUE TITLE
epic2 does not work for custom genome

### ISSUE THREAD

**Issue by Turckie** [biocore-ntnu/epic2#69]
Although in absence of genome data in the epic2 repository the program should work with only chromosizes and effective genome fraction, in our case is does not. We have tried to add our genome data within epic, but did not manage to make it run.
This is the error message:
Traceback (most recent call last):
  File "/scratch/ngscourse/lib/miniconda/bin/epic2", line 257, in <module>
    _main(args)
  File "/scratch/ngscourse/lib/miniconda/lib/python3.10/site-packages/epic2/main.py", line 35, in _main
    effective_genome_length, chromsizes = egl_and_chromsizes(args)
  File "epic2/src/genome_info.pyx", line 352, in epic2.src.genome_info.egl_and_chromsizes
  File "epic2/src/genome_info.pyx", line 240, in epic2.src.genome_info.create_genome_size_dict

**Comment by endrebak** [comment]
Are you able to share the data with me?

**Comment by Turckie** [comment]
Thank you for the response! I solved the problem of providing a custom chromosome file. I had an empty line at the end of the file which lead to the error. After correcting that, the analysis run through.

That being said, I would prefer to add my genome to the database and provide the calculated effective genome size for different read length with epic-effective that worked with epic but seems not part of epic2. Could you please write a little instruction where exactely the files go and possibly include epic2-effective?
I work with plant genomes which are often missing in the genome databases.
Thanks,
Franziska

Sent from Nine
________________________________
Von: "endrebak.ada" ***@***.***>
Gesendet: Sonntag, 30. April 2023 11:22
An: biocore-ntnu/epic2
Cc: Franziska; Author
Betreff: Re: [biocore-ntnu/epic2] epic2 does not work for custom genome (Issue #69) 

Are you able to share the data with me?
