### ISSUE TITLE
Int overflow when parsing ChIP files.

### ISSUE THREAD

**Issue by vidal-adrien** [biocore-ntnu/epic2#74]
Hello, an error occurred when trying your tool to do a single-end peak calling. The genome is the dm6 drosophila assembly.

Running on conda 23.9.0 with python: 3.7.16

Thanks,

Adrien.

Here's the full terminal log:
```

(epic2-0.0.41) vidal@bioclusts05:/kingdoms/mpb/workspace32/vidal/TEST$ epic2 --chromsizes ${chromsizes_tab} --fragment-size ${fragment_size} --treatment ${IP_bam} --control ${Input_bam} > ${output_peaks}
Found a median readlength of 50.0
 
Using chromosome sizes found in /import/pr_aralight_processed/shared_genomic_resources/genomes/Drosophila_melanogaster_dm6/regions/dm6_chromSizes.tsv.
 
Using an effective genome length of ~124 * 1e6
 
Parsing ChIP file(s): 
  /kingdoms/mpb/workspace32/vidal/Analyses/Chip-Rx__Martin_H3K27me3+H2Bub__Col-CEN_v_TAIR10/bam_h3k27me3_TAIR10/h3k27me3_IP_ALL.drosophila.sorted.filtered.dedup.masked.merged.bam 
Traceback (most recent call last):
  File "/users/mpb/vidal/.conda/envs/epic2-0.0.41/bin/epic2", line 248, in <module>
    _main(args)
  File "/users/mpb/vidal/.conda/envs/epic2-0.0.41/lib/python3.7/site-packages/epic2/main.py", line 40, in _main
    args["treatment"], args, "ChIP")
  File "epic2/src/reads_to_bins.pyx", line 183, in epic2.src.reads_to_bins.files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 309, in epic2.src.reads_to_bins.files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 61, in epic2.src.reads_to_bins.remove_out_of_bounds_bins
OverflowError: Python int too large to convert to C long
```

**Comment by vidal-adrien** [comment]
Update: The issue did not occur when using `--autodetect-chroms` rather than using a chromome sizes file.

**Comment by vidal-adrien** [comment]
Nevermind this entire issue. I didn't realize I got an old version (0.0.41) of epic2 through conda instead of the current one (0.0.52). 

The bug does not occur with the current version.

For anyone reading this who has the same issue, you may want to use the `conda-forge` source.

`conda install -c conda-forge -c bioconda epic2=0.0.52` (or whatever the latest version is at time of reading)

**Comment by endrebak** [comment]
Thanks for resolving this :D
