### ISSUE TITLE
EPIC2 can't use 

### ISSUE THREAD

**Issue by anyang-kevin** [biocore-ntnu/epic2#75]
Hi,
I used conda to install epic2 in a new environment and the python version is 3.5.6. But epic2 has an error in pysam module when I used epic2 --help.
`Traceback (most recent call last):
  File "/public/home/anyang/tool/conda/miniconda3/envs/epic/bin/epic2", line 10, in <module>
    from epic2.src.reads_to_bins import files_to_bin_counts
  File "epic2/src/reads_to_bins.pyx", line 14, in init epic2.src.reads_to_bins
  File "libchtslib.pxd", line 2590, in init epic2.src.read_bam
AttributeError: module 'pysam.libchtslib' has no attribute 'HTSFile'
`
By the way, it's too hard to install epic2 by conda. It will solving environment for a long time even in a new environment.

**Comment by anyang-kevin** [comment]
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    curl-7.88.1                |       h37d81fd_2          81 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    cython-0.28.5              |   py35hf484d3e_0         2.8 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    epic2-0.0.16               |   py35h4e20536_0         9.9 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    htslib-1.9                 |       ha228f0b_7         1.5 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    intel-openmp-2022.1.0      |    h9e868ea_3769         4.5 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    krb5-1.20.1                |       h568e23c_1         1.3 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    libcurl-7.88.1             |       h91b91d3_2         383 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    libedit-3.1.20230828       |       h5eee18b_0         179 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    mkl-2018.0.3               |                1       126.9 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    numpy-1.14.2               |   py35hdbf6ddf_0         3.3 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
    pysam-0.8.4                |           py35_0        12.1 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
    scipy-1.1.0                |   py35hd20e5f9_0        13.3 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
here is the total package when i install epic2

**Comment by endrebak** [comment]
There is something weird about your htslib. Have you tried just pip installing?

**Comment by anyang-kevin** [comment]
> There is something weird about your htslib. Have you tried just pip installing?

Sorry, I am unable to use pip to install packages due to the requirement for maintaining system dependencies. Could you provide a conda version which can be used?

**Comment by endrebak** [comment]
This seems first and foremost to be an HTSlib issue.

**Comment by anyang-kevin** [comment]
Hello,
I try to install epic2 by pip and I recived error with pysam.
`      File "/public/home/pip-build-77gjoy9u/epic2/setup.py", line 3, in <module>
        import pysam
    ModuleNotFoundError: No module named 'pysam'
`
also , i cant install pysam by pip because of wheel error. It looks like conflict between linux and pip. I think an effective version of conda is critical.
By the way, can epic2 handle duplicates samples in call peak?
